### ISSUE TITLE
Not picking up local config?

### ISSUE THREAD

**Issue by bobrocke** [bleutzinn/grav-plugin-add-page-by-form#37] opened 2019-02-02 23:10 UTC
At /user/config/plugins/add-page-by-form.yaml I have this configuration:
```
default_title: 'My New Post'
default_content: 'Wite the blog post contents here...'
auto_taxonomy_types: true
```
But the form page does not use the title, nor content fields as defaults.

Do I have the config in the wrong place?

**Comment by bleutzinn** [comment] 2019-03-03 15:17
Adding the label "bug" to this issue appeared to be premature.

The plugin config default values are being used as intended.
Just to clarify: The value for `default_title` is used when there is no `title` variable used in the 'pagefrontmatter' block nor as a form field. The same goes for `default_content`.

Also any new taxonomy types do get added to the site configuration (in`site.yaml`).

The examples in the ReadMe do not show how to add a new taxonomy type though. I even had to re-invent my own wheel again to find out, hence my reference in [#36](https://github.com/bleutzinn/grav-plugin-add-page-by-form/issues/36#issuecomment-460063259).

To add new taxonomy types you should define them like this is the form:
```
pagefrontmatter:
    taxonomy:
        business: consulting
```
Actually, the value `consulting` is optional here.

The new taxonomy type `business` is added to the already defined taxonomy types in `site.yaml`. Assuming no other types have been added to the two default taxonomy types (`category` and `tag`) this is the relevant section in `site.yaml`:
```
taxonomies:
  - category
  - tag
  - business
```

To allow the creator of the new page to enter extra values to the taxonomy type `business` simply add a form field like this:
```
form:
    name: addpage-form
    fields:
        -
            name: taxonomy.business
            label: 'Enter Business topics (comma separated)'
            type: text
```

The new taxonomy type plus it's values are then present in the new page frontmatter. Suppose the user has entered "marketing, PR" in the form field `taxonomy.business` then this will be in the new page frontmatter:
```
taxonomy:
    business:
        - consulting
        - marketing
        - PR
```

I hope this clarifies things a bit.

**Closed by bleutzinn** 2019-03-03 15:17 UTC
Labels: question
